// Generated by https://quicktype.io

export interface singlCar {
  image:           Image;
  _id:             string;
  name:            string;
  rate:            number;
  reviewsCount:    number;
  passengers:      number;
  transmissions:   string;
  airConditioning: boolean;
  doors:           number;
  price:           number;
  createdAt:       Date;
  updatedAt:       Date;
  __v:             number;
}

export interface Image {
  id:  string;
  url: string;
}
